config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  resources :users, only: [:show] do
    resources :items, only: [:create, :destroy]
  end
 
    
  authenticated :users do
    root to: 'users#show', as: :authenticated_root
  end 
  
  get 'welcome/index'

  get 'welcome/about'
  
  root 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
    
    belongs_to :user
  
    #validates :rank, presence: true
    validates :task, presence: true, length: { minimum: 1 }
    #validates :completed, inclusion: [true, false]
    validates :user, presence: true
    
    default_scope { order('updated_at DESC') }
    
    private 
    
    def self.default_scope
        Item.where("updated_at >= ?", Time.now - 7.days)
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  has_many :items
  attr_accessor :login

  
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :confirmable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  
  
  
  def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
          where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
        else
        if conditions[:email].nil?
          where(conditions).first
        else
          where(email: conditions[:email]).first
        end
      end
  end
  
  def avatar_url
    	gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    	"http://gravatar.com/avatar/#{gravatar_id}.png?s"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?
  

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

    
    def create
    	@user = User.find(params[:user_id])
    	@item = @user.items.new(item_params)
    	@item.user = current_user
    	@new_item = Item.new
    
 
    	if @item.save
    		flash.now[:notice] = "Item added successfully."
    	else
    		flash.now[:alert] = "Item failed to be added."
    	end
    	
    	respond_to do |format|
            format.html
            format.js
        end
    end
    
    def destroy
    	@user = User.find(params[:user_id])
    	@item = @user.items.find(params[:id])
 
    	if @item.destroy
    	    if (@user.items.count) > 0
    		  flash[:notice] = "One down...only #{@user.items.count} more to go!"
    		else
    		  flash[:notice] = "Boom..finished"
    	    end 
    	else
    		flash[:alert] = "Task couldn't be deleted. Try again."
    	end
    	
    	respond_to do |format|
    		format.html
    		 format.js 
    	end
    end

    
private
 
  def item_params
     params.require(:item).permit( :task )  ## Add => :rank, :completed later
  end
  
  def distance_of_time_in_words
      from_time = @item.created_at
      to_time = 7.days
      from_time + to_time
  end
      
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	
	def show
		@user = User.find(params[:id] || current_user.id)
		@items = @user.items
	end
	
	
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to user_path(current_user) if current_user
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def form_group_tag(errors, &block)
    	css_class = 'form-group'
    	css_class << ' has-error' if errors.any?
    	content_tag :div, capture(&block), class: css_class
	end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for [user, item], remote: true do |f| %>

   
   <div class="row">
               <%= f.label :task %>
         <div class="input-group">
               <%= f.text_field :task, class: "form-control", placeholder: "Add to-do item" %>
         <span class="input-group-btn">
               <%= f.submit "Add", class: 'btn btn-success' %>
         </span>
        
      </div>
   
   
<!--  Add ## => later
#               <div class="form-group">
#                <%= f.label :rank %>
#                 <%= f.text_field :rank, class: 'form-control', placeholder: "Add to-do item" %>
#               </div>
#               
#               <div class="field">
#                        <%= f.check_box :completed %>
#                        <%= f.label :completed %>
#                      </div>
#              
#               
#               <div class="form-group">
#                 <%= f.submit "Add", class: 'btn btn-success' %>
#               </div>
-->
<% end %>
</div>

app/views/items/_item.html.erb
<%= content_tag :li, class: 'list-group-item', id: "item-#{item.id}" do %>
    
    <%= item.task %> | <%= link_to "Completed",[ item.user, item ], method: :delete, remote: true, class: 'glyphicon glyphicon-ok' %><span class="badge"><%= distance_of_time_in_words(Time.now, item.created_at + 7.days) %></span>
    
<% end %>

app/views/items/create.js.erb
 <% if @item.valid? %>
   $('.js-items').prepend("<%= escape_javascript(render(@item)) %>");
   $('.new-item').html("<%= escape_javascript(render partial: 'items/form', locals: { user: @user, item: @new_item }) %>");
   $('.flash').prepend("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:notice] %></div>");
 <% else %>
   $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
   $('.new-item').html("<%= escape_javascript(render partial: 'items/form', locals: { user: @user, item: @item }) %>");
 <% end %>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
    $('#item-<%= @item.id %>').hide();
    $('.flash').prepend("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:notice] %></div>");
<% else %>
    $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= flash.now[:alert] %></div>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <nav class="navbar navbar-default">
                <div class="container-fluid">
                    <div class="row navrow">
                        
                        <% if user_signed_in? %>
                        <div class="col-md-3">
                              <div class="navbar-header">
                                  <div class="hovereffect">
                                      <%= image_tag (current_user.avatar_url), class: "img-responsive" %>
                                      <div class="overlay">
                                          <h2>Edit Profile</h2>
                                          <a class="info" href="/users/edit"></a>
                                      </div>
                                  </div>
                              </div>
                        </div>
                        <div class="col-md-6">
                            <ul class="nav nav-tabs nav-justified">
                                <li><%= link_to "To-do List", welcome_index_path %></li>
                                <li><%= link_to "About", welcome_about_path %></li>
                            </ul>
                        </div>
                        <div class="col-md-3 nav">
                            <div class="pull-right user-info" >
                                    Signed in as: <strong><%= current_user.username %></strong> | <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                            </div>
                        </div>
                        
                        <% else %>
                        <div class="col-md-6 col-md-offset-3">
                            <ul class="nav nav-tabs nav-justified">
                                <li><%= link_to "Blocitoff", welcome_index_path %></li>
                                <li><%= link_to "About", welcome_about_path %></li>
                            </ul>
                        </div>
                        <div class="col-md-3 nav">
                            <div class="pull-right ">
                                <div class="btn-group" role="group" aria-label="...">
                                    <button type="button" class="btn btn-default"><%= link_to "Sign In", new_user_session_path %></button>
                                    <button type="button" class="btn btn-default"><%= link_to "Sign Up", new_user_registration_path %></button>
                                </div>
                            </div>
                        </div>
                        <% end %>
                    
                    </div>
                </div>
            </nav>
        </div>
    </div>
    
    <div class="flash">
       <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash.now[:alert] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash.now[:alert] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>
    </div>
   
    <%= yield %>
    
</div>
</body>
</html>

app/views/users/show.html.erb
<body onload="myFunction()">
    <script>
        function myFunction() {
            blocmetrics.report('users#show');
        }
    </script>
<div class="row">
    <div class="col-md-8.col-md-offset-2">
        <div class="media">
            <div class="media-body">
                <div class="page-header">
                    <h1 class="text-center"><%= current_user.username.capitalize! %>'s <small>To-Do List</small></h1><br />
                </div>
            <div class="col-md-6 col-md-offset-3">
            <div class='js-items'>
                <%= render @user.items %>
            </div>
            <% if current_user %>
                <div class="new-item">
                    <%= render 'items/form', item: Item.new, user: @user %>
                </div>
            <% end %>
            </div>
            </div>
        </div>
    </div>
</div>
</body>

app/views/welcome/about.html.erb
<h1 class="bg-success">About Blocitoff</h1>
 <h3>Created by:</h3>
 <p>Bloc Student - Josh Van Wyk</p>
 <p>Bloc Mentor - Mark Carpenter</p>

app/views/welcome/index.html.erb
<body onload="myFunction()">
    <script>
        function myFunction() {
            blocmetrics.report('welcome#index');
        }
    </script>
<br>
<div class="jumbotron">
    <h1>Blocitoff</h1>
    <p>To do, or not to do...either way, it will be gone after 7 days.</p>
    
    <p>
     <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
    </p>
</div>
</body>